name: Build

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Build
        run: make build 
      - name: Release
        uses: softprops/action-gh-release@v2